### ISSUE TITLE
How do you measure the memory of data structures?

### ISSUE THREAD

**Issue by KINGFIOX** [schencoding/peahash#3]
How do you measure the memory of data structures?

I found the same memory size of different skew, when using the gperftools. Maybe the method I used is wrong.

**Comment by DrWereviruswolf** [comment]
I add a global memory counter in the original code. The counter increases when an allocate() fuction is called.  The counter decreases after a reclamation function. I don't think that gperf can distinguish the memory pool, the memory pre-allocated for key-value pairs to insert and memory allocated dynamically for a hash table (which is the true memory of a data structure).

**Comment by KINGFIOX** [comment]
ok, thank you
